//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyData
    {
        public string Ticker { get; set; }
        public string CompanyName { get; set; }
        public string Sector { get; set; }
        public string Industry { get; set; }
        public string DividendYield { get; set; }
        public string Beta { get; set; }
        public string PBV_MRQ { get; set; }
        public string PE_2017 { get; set; }
        public string PE_2018 { get; set; }
        public string PE_2019 { get; set; }
        public string PE_2020 { get; set; }
        public string PS_2017 { get; set; }
        public string PS_2018 { get; set; }
        public string PS_2019 { get; set; }
        public string PS_2020 { get; set; }
        public string EVEBITDA_2017 { get; set; }
        public string EVEBITDA_2018 { get; set; }
        public string EVEBITDA_2019 { get; set; }
        public string EVEBITDA_2020 { get; set; }
        public string EPS_FY2017_Mean { get; set; }
        public string EPS_FY2018_Mean { get; set; }
        public string EPS_FY2019_Mean { get; set; }
        public string EPS_FY2020_Mean { get; set; }
        public string Revenue_FY2017_Mean { get; set; }
        public string Revenue_FY2018_Mean { get; set; }
        public string Revenue_FY2019_Mean { get; set; }
        public string Revenue_FY2020_Mean { get; set; }
        public string EPS_Q12017_Mean { get; set; }
        public string EPS_Q12017_Low { get; set; }
        public string EPS_Q12017_High { get; set; }
        public string Revenue_Q12017_Mean { get; set; }
        public string Revenue_Q12017_Low { get; set; }
        public string Revenue_Q12017_High { get; set; }
    }
}
