//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarterly
    {
        public string Ticker { get; set; }
        public string EPS_Estimate_Mean { get; set; }
        public string EPS_Estimate_Low { get; set; }
        public string EPS_Estimate_High { get; set; }
        public string Revenue_Estimate_Mean { get; set; }
        public string Revenue_Estimate_Low { get; set; }
        public string Revenue_Estimate_High { get; set; }
        public string EPS_FY_2017 { get; set; }
        public string EPS_FY_2018 { get; set; }
        public string EPS_FY_2019 { get; set; }
        public string EPS_FY_2020 { get; set; }
        public string Revenue_FY_2017 { get; set; }
        public string Revenue_FY_2018 { get; set; }
        public string Revenue_FY_2019 { get; set; }
        public string Revenue_FY_2020 { get; set; }
        public string PE_2017 { get; set; }
        public string PE_2018 { get; set; }
        public string PE_2019 { get; set; }
        public string PE_2020 { get; set; }
        public string PS_2017 { get; set; }
        public string PS_2018 { get; set; }
        public string PS_2019 { get; set; }
        public string PS_2020 { get; set; }
        public string EV_EBITDA_2017 { get; set; }
        public string EV_EBITDA_2018 { get; set; }
        public string EV_EBITDA_2019 { get; set; }
        public string EV_EBITDA_2020 { get; set; }
        public string PBV_MRQ { get; set; }
        public string Dividend_Yield { get; set; }
        public string Beta { get; set; }
        public string CompanyName { get; set; }
    }
}
