//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTWS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RewardTheRiskEntities : DbContext
    {
        public RewardTheRiskEntities()
            : base("name=RewardTheRiskEntities")
        {
            // Edit here the specific connection details
            this.Database.Connection.ConnectionString = "data source=***.***.**.***;initial catalog=RewardTheRisk;persist security info=True;user id=*****;Password=*****";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyData> CompanyData { get; set; }
    }
}
